SF:lib/core/errors/exception.dart
DA:7,3
DA:9,1
DA:10,3
LF:3
LH:3
end_of_record
SF:lib/src/authentication/data/datasource/authentication_remote_data_source.dart
DA:25,1
DA:27,1
DA:34,2
DA:35,1
DA:36,1
DA:37,1
DA:43,1
DA:48,3
DA:49,0
DA:50,0
DA:51,0
DA:54,1
DA:57,1
DA:58,1
DA:64,1
DA:67,2
DA:68,1
DA:71,2
DA:72,1
DA:73,1
DA:74,1
DA:78,1
DA:79,2
DA:81,1
DA:82,2
DA:84,1
DA:85,1
DA:88,0
DA:89,0
LF:29
LH:24
end_of_record
SF:lib/src/authentication/data/models/user_model.dart
DA:7,4
DA:14,2
DA:15,0
DA:21,1
DA:22,2
DA:24,2
DA:25,2
DA:26,2
DA:27,2
DA:28,2
DA:29,2
DA:32,4
DA:33,2
DA:34,2
DA:35,2
DA:36,2
DA:39,3
DA:41,1
DA:47,1
DA:48,1
DA:49,0
DA:50,1
DA:51,1
LF:23
LH:21
end_of_record
SF:lib/src/authentication/domain/entities/user.dart
DA:9,5
DA:16,1
DA:17,0
DA:23,2
DA:24,8
LF:5
LH:4
end_of_record
SF:lib/core/errors/failure.dart
DA:8,2
DA:10,4
DA:12,1
DA:13,3
DA:17,2
DA:22,1
DA:23,1
DA:24,1
DA:25,1
LF:9
LH:9
end_of_record
SF:lib/core/usecase/usecase.dart
DA:4,1
DA:10,1
LF:2
LH:2
end_of_record
SF:lib/src/authentication/domain/repositories/authentication_repository.dart
DA:5,0
LF:1
LH:0
end_of_record
SF:lib/src/authentication/domain/usecases/create_user.dart
DA:9,1
DA:11,1
DA:12,2
DA:13,1
DA:14,1
DA:15,1
DA:24,3
DA:30,2
DA:31,0
DA:36,1
DA:38,4
LF:11
LH:10
end_of_record
SF:lib/src/authentication/domain/usecases/get_users.dart
DA:9,1
DA:11,1
DA:12,2
LF:3
LH:3
end_of_record
SF:lib/src/presentation/cubit/authentication_cubit.dart
DA:12,1
DA:17,1
DA:19,1
DA:24,1
DA:26,2
DA:27,1
DA:34,1
DA:35,2
DA:36,2
DA:38,2
DA:44,1
DA:45,1
DA:47,2
DA:49,1
DA:50,2
DA:51,2
DA:53,3
LF:17
LH:17
end_of_record
SF:lib/src/presentation/cubit/authentication_state.dart
DA:4,8
DA:6,1
DA:7,1
DA:11,7
DA:15,7
DA:19,7
DA:23,7
DA:29,2
DA:31,1
DA:32,1
DA:33,1
DA:34,0
DA:36,1
DA:42,1
DA:44,1
DA:45,2
LF:16
LH:15
end_of_record
SF:lib/src/authentication/data/repositories/authentication_repository_implementation.dart
DA:13,1
DA:15,1
DA:22,2
DA:29,1
DA:30,1
DA:31,1
DA:36,1
DA:39,2
DA:40,1
DA:41,1
DA:42,1
DA:43,1
LF:12
LH:12
end_of_record
